name: publish

on:
  push:
    tags:
      - 'v*'

env:
  MISE_EXPERIMENTAL: true
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run prepack
      # - uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      # - run: pnpm run postpack
      - run: mise run oclif:pack:tarballs
