name: tests

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

env:
  MISE_EXPERIMENTAL: true
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}

jobs:
  unit-tests:
    strategy:
      matrix:
        # os: ['ubuntu-latest']
        os: ['self-hosted']
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      # - uses: pnpm/action-setup@v4
      #   with:
      #     version: 9
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node_version }}
      #     cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
